Add optional UI reporting.
discoverygarden/islandora_job pull request #39
Opened 2019-06-14 17:19 UTC by jordandukart

2019-06-19 18:07 UTC, qadan requested changes

2019-06-19 18:07 UTC, qadan commented on includes/admin.form.inc
> +    $connection = $form_state['values']['islandora_job_display_messages_remote_database'] === 1 ? Database::getConnection('default', 'gearman_queue') : $connection = Database::getConnection();
`$connection = ... : $connection = Database::getConnection()` unnecessary reassignment at the end of the ternary

2019-06-19 18:07 UTC, qadan commented on islandora_job.module
> +      '!like' => db_like($object->id),
I might be off on this, but aren't these `db_like()`s too inclusive? e.g., the message would display for `pid:1` but also `pid:10`, etc.? Same as the URL, would find `http://drupal/site` and `http://drupal/site2`? Should this perhaps enclose the likes in a single quote to catch the full JSON string?

2019-06-20 17:55 UTC, jordandukart commented on islandora_job.module
> +      '!like' => db_like($object->id),
Was too inclusive with the PID, site seems to be good because of the json_encoding. Tested on a box with multi-sites.

2019-06-21 12:44 UTC, merged